// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.35;

import {MemeverseRegistrarAbstract} from "./MemeverseRegistrarAbstract.sol";
import {IMemeverseRegistrarAtLocal} from "../interfaces/IMemeverseRegistrarAtLocal.sol";
import {IMemeverseRegistrar, IMemeverseRegistrationCenter} from "../interfaces/IMemeverseRegistrar.sol";
import {MemeverseRegistrationLib} from "../libraries/MemeverseRegistrationLib.sol";

/**
 * @title Local MemeverseRegistrar for deploying memecoin and registering memeverse
 */
contract MemeverseRegistrarAtLocal is IMemeverseRegistrarAtLocal, MemeverseRegistrarAbstract {
    address public registrationCenter;

    constructor(address _owner, address _registrationCenter, address _memeverseLauncher, address _memeverseCommonInfo)
        MemeverseRegistrarAbstract(_owner, _memeverseLauncher, _memeverseCommonInfo)
    {
        require(_registrationCenter != address(0), ZeroAddress());
        registrationCenter = _registrationCenter;
    }

    /// @notice Quotes the center-chain registration fee for the local registrar path.
    /// @dev The local registrar does not perform a registrar-to-center LayerZero send, so `value` is ignored here.
    /// The returned fee only covers the registration center's outbound remote fan-out, if any.
    /// @param param Registration request to be submitted to the center.
    /// @param value Unused placeholder kept for interface compatibility with the omnichain registrar.
    /// @return lzFee Native fee required by the registration center.
    function quoteRegister(IMemeverseRegistrationCenter.RegistrationParam calldata param, uint128 value)
        external
        view
        override
        returns (uint256 lzFee)
    {
        value;
        uint32[] memory omnichainIds = MemeverseRegistrationLib.deduplicate(param.omnichainIds);
        (,, uint192 currentNonce) = IMemeverseRegistrationCenter(registrationCenter).symbolRegistry(param.symbol);
        uint256 centerDay = IMemeverseRegistrationCenter(registrationCenter).DAY();
        uint256 endTimeRaw = block.timestamp + param.durationDays * centerDay;
        require(endTimeRaw <= MemeverseRegistrationLib.MAX_END_TIME, IMemeverseRegistrationCenter.InvalidInput());

        uint64 endTime = uint64(endTimeRaw);
        uint64 unlockTime = uint64(endTimeRaw + MemeverseRegistrationLib.FIXED_LOCKUP_DURATION);
        IMemeverseRegistrar.MemeverseParam memory memeverseParam = IMemeverseRegistrar.MemeverseParam({
            name: param.name,
            symbol: param.symbol,
            uri: param.uri,
            desc: param.desc,
            communities: param.communities,
            uniqueId: MemeverseRegistrationLib.deriveUniqueId(param.symbol, currentNonce + 1, param.uAsset),
            endTime: endTime,
            unlockTime: unlockTime,
            omnichainIds: omnichainIds,
            uAsset: param.uAsset,
            flashGenesis: param.flashGenesis
        });
        (lzFee,,) = IMemeverseRegistrationCenter(registrationCenter).quoteSend(omnichainIds, abi.encode(memeverseParam));
    }

    /// @notice Registers the memeverse on the local chain.
    /// @dev Only the registration center may call this entrypoint after symbol validation succeeds.
    /// @param param Fully expanded memeverse configuration generated by the registration center.
    function localRegistration(MemeverseParam calldata param) external override {
        require(msg.sender == registrationCenter, PermissionDenied());

        _registerMemeverse(param);
    }

    /// @notice Forwards a local registration request into the registration center.
    /// @dev `value` is the forwarded center gas/native budget and must match `msg.value`; it may exceed the
    /// center's current quote, with any hub/center residual handled by the registration center as gas dust.
    /// @param param Registration request to submit.
    /// @param value Forwarded center gas/native budget; must equal `msg.value`.
    function registerAtCenter(IMemeverseRegistrationCenter.RegistrationParam calldata param, uint128 value)
        external
        payable
        override
    {
        require(msg.value == value, IMemeverseRegistrationCenter.InvalidInput());
        IMemeverseRegistrationCenter(registrationCenter).registration{value: value}(param);
    }

    /// @notice Updates the registration center trusted by this registrar.
    /// @dev Only callable by the owner.
    /// @param _registrationCenter New registration center address.
    function setRegistrationCenter(address _registrationCenter) external override onlyOwner {
        require(_registrationCenter != address(0), ZeroAddress());

        registrationCenter = _registrationCenter;

        emit SetRegistrationCenter(_registrationCenter);
    }
}
